import * as React from 'react'
import { Loader2, FileText, Home, User, Settings, LogOut, Menu, X, ChevronDown, Sun, Moon, Laptop, Plus, Trash2, Edit, Download, Check, AlertTriangle, Info, ExternalLink, Copy, CheckCircle2, XCircle, AlertCircle, MessageSquare, FileQuestion, FileUp, FileDown, FileCheck, FileX, FileClock, FileSearch, FileEdit, FileBarChart2, FileCode, FileInput, FileOutput, FileScan, FileSpreadsheet, FileType, FileVideo, FileVolume2, FileWarning, FileX2, File, Folder, FolderOpen, FolderPlus, FolderMinus } from 'lucide-react'

export const Icons = {
  spinner: Loader2,
  file: File,
  fileText: FileText,
  home: Home,
  user: User,
  settings: Settings,
  logOut: LogOut,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  plus: Plus,
  trash: Trash2,
  edit: Edit,
  download: Download,
  check: Check,
  alertTriangle: AlertTriangle,
  info: Info,
  externalLink: ExternalLink,
  copy: Copy,
  checkCircle: CheckCircle2,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  messageSquare: MessageSquare,
  fileQuestion: FileQuestion,
  fileUp: FileUp,
  fileDown: FileDown,
  fileCheck: FileCheck,
  fileX: FileX,
  fileClock: FileClock,
  fileSearch: FileSearch,
  fileEdit: FileEdit,
  fileBarChart2: FileBarChart2,
  fileCode: FileCode,
  fileInput: FileInput,
  fileOutput: FileOutput,
  fileScan: FileScan,
  fileSpreadsheet: FileSpreadsheet,
  fileType: FileType,
  fileVideo: FileVideo,
  fileVolume2: FileVolume2,
  fileWarning: FileWarning,
  fileX2: FileX2,
  folder: Folder,
  folderOpen: FolderOpen,
  folderPlus: FolderPlus,
  folderMinus: FolderMinus,
}
